CREATE TABLE IF NOT EXISTS STAFF (
    StaffID INT PRIMARY KEY AUTO_INCREMENT,
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50),
    PhoneNumber CHAR(10),
    Email NVARCHAR(100),
    StartDate DATE,
    EmployeeType NVARCHAR(100)
);

CREATE TABLE IF NOT EXISTS HOTEL (
    HotelID INT PRIMARY KEY AUTO_INCREMENT,
    Street NVARCHAR(100),
    City NVARCHAR(50),
    State VARCHAR(2),
    ZipCode VARCHAR(5),
    NumberOfRooms INT NOT NULL DEFAULT 0,
    HotelManagerID INT,
    CONSTRAINT hotel_manager_fk FOREIGN KEY (HotelManagerID) REFERENCES STAFF(StaffID)
);

CREATE TABLE IF NOT EXISTS AMENITY (
    AmenityID INT PRIMARY KEY AUTO_INCREMENT,
    AmenityName NVARCHAR(100)
);

CREATE TABLE IF NOT EXISTS HOTEL_AMENITY (
    HotelID INT,
    AmenityID INT,
    PRIMARY KEY (HotelID,AmenityID),
    CONSTRAINT hotelamenity_hotelid_fk FOREIGN KEY (HotelID) REFERENCES HOTEL(HotelID),
    CONSTRAINT hotelamenity_amenityid_fk FOREIGN KEY (AmenityID) REFERENCES AMENITY(AmenityID)
);

CREATE TABLE IF NOT EXISTS SHIFT (
    ShiftID INT PRIMARY KEY AUTO_INCREMENT,
    HotelID INT NOT NULL,
    StaffID INT NOT NULL,
    ShiftPosition NVARCHAR(100),
    ShiftStart DATETIME,
    ShiftEnd DATETIME,
    CONSTRAINT shift_hotelid_fk FOREIGN KEY (HotelID) REFERENCES HOTEL(HotelID),
    CONSTRAINT shift_staffid_fk FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID)
);

CREATE TABLE IF NOT EXISTS ROOM (
    RoomID INT PRIMARY KEY AUTO_INCREMENT,
    HotelID INT NOT NULL,
    RoomNumber INT NOT NULL,
    RoomType NVARCHAR(50),
    RoomPrice DOUBLE,
    CONSTRAINT room_hotelid_fk FOREIGN KEY (HotelID) REFERENCES HOTEL(HotelID)
);

CREATE TABLE IF NOT EXISTS FEATURE (
    FeatureID INT PRIMARY KEY AUTO_INCREMENT,
    FeatureName NVARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ROOM_FEATURE (
    RoomID INT,
    FeatureID INT,
    PRIMARY KEY (RoomID, FeatureID),
    CONSTRAINT roomfeature_roomid_fk FOREIGN KEY (RoomID) REFERENCES ROOM(RoomID),
    CONSTRAINT roomfeature_featureid_fk FOREIGN KEY (FeatureID) REFERENCES FEATURE(FeatureID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    CustomerID INT PRIMARY KEY AUTO_INCREMENT,
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50),
    DateOfBirth DATE,
    Street NVARCHAR(100),
    City NVARCHAR(50),
    State VARCHAR(2),
    ZipCode VARCHAR(5),
    PhoneNumber CHAR(10),
    Email NVARCHAR(100)
);

CREATE TABLE IF NOT EXISTS RESERVATION (
    ReservationID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID INT NOT NULL,
    CheckIn DATETIME,
    CheckOut DATETIME,
    CONSTRAINT reservation_customerid_fk FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);

CREATE TABLE IF NOT EXISTS ROOM_RESERVATION (
    RoomID INT,
    ReservationID INT,
    PRIMARY KEY (RoomID, ReservationID),
    CONSTRAINT roomreservation_roomid_fk FOREIGN KEY (RoomID) REFERENCES ROOM(RoomID),
    CONSTRAINT roomreservation_reservationid_fk FOREIGN KEY (ReservationID) REFERENCES RESERVATION(ReservationID)
);

CREATE TABLE IF NOT EXISTS PAYMENT (
    PaymentID INT PRIMARY KEY AUTO_INCREMENT,
    ReservationID INT NOT NULL,
    PaymentType NVARCHAR(100),
    PaymentInfo NVARCHAR(200),
    CONSTRAINT payment_reservationid_fk FOREIGN KEY (ReservationID) REFERENCES RESERVATION(ReservationID)
);

COMMIT;